service: skycatch-project
#app: your-app-name
#tenant: your-tenant-name

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["ImageDataTable", "Arn"] }
        - { "Fn::Join": ["", ["Fn::GetAtt": ["ImageDataTable", "Arn"], "/index/*"]] }
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::skycatch-test-photos/*"
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  ServiceFunction:
    handler: bin/service
    timeout: 120
    environment:
      DYNAMO_TABLE_IMAGE_DATA: ${self:resources.Resources.ImageDataTable.Properties.TableName}
    events:
      - s3:
          bucket: skycatch-test-photos
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpg

# you can add CloudFormation resource templates here
resources:
  Resources:
    ImageDataTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: etag
            AttributeType: S
        KeySchema:
          - AttributeName: etag
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}-image-data
